# Configuration for typos spell checker
# https://github.com/crate-ci/typos

[default]
extend-ignore-re = [
    "https?://[^\\s]+", # Ignore URLs
    "'gASV[^']+",       # Ignore base64-encoded pickle data
]

[default.extend-words]
consts = "consts"  # Common abbreviation for "constants" used in apify_shared.consts

[files]
# Extend the default exclude list
extend-exclude = [
    "*.lock",
    "*.min.js",
    "*.min.css",
    "CHANGELOG.md",
]
